---
exclude: ['params.json']
pygments: true
safe: true
permalink: /:categories/:title

name: Jacob Redding
url: http://jredding.github.io/new-site/
author: Jacob Redding
email: Jacobredding@gmail.com
# ga: 'UA-XXXXXXX-X'
